services:
  # SAB Lanyard MongoDB Database
  mongodb:
    image: mongo:6.0
    container_name: amdstore_mongodb
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME:-amdadmin}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD:-amdpassword123}
      MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE:-amdstore}
      TZ: ${TZ:-Asia/Ho_Chi_Minh}
    expose:
      - "27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - amdstore_network
    healthcheck:
      test: |
        mongosh --quiet \
          --username "$${MONGO_INITDB_ROOT_USERNAME}" \
          --password "$${MONGO_INITDB_ROOT_PASSWORD}" \
          --authenticationDatabase admin \
          --eval 'db.adminCommand("ping").ok' | grep -q 1
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  # SAB Lanyard MinIO Object Storage
  minio:
    image: minio/minio:latest
    container_name: amdstore_minio
    restart: unless-stopped
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER:-minioadmin}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD:-minioadmin123}
      TZ: ${TZ:-Asia/Ho_Chi_Minh}
    volumes:
      - minio_data:/data
    networks:
      - amdstore_network
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9000/minio/health/live" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  # SAB Lanyard Backend API
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    pull_policy: always
    container_name: amdstore_backend
    restart: unless-stopped
    env_file:
      - .env
    environment:
      # Override specific env vars if needed, otherwise use from .env file
      NODE_ENV: ${NODE_ENV}
      PORT: ${BACKEND_PORT}
      BASE_URL: ${BACKEND_URL}
      MONGODB_URI: ${MONGODB_URI}
      JWT_SECRET: ${JWT_SECRET}
      ADMIN_EMAIL: ${ADMIN_EMAIL}
      ADMIN_USERNAME: ${ADMIN_USERNAME}
      ADMIN_PASSWORD: ${ADMIN_PASSWORD}
      APPSCRIPT_URL: ${APPSCRIPT_URL}
      CORS_ORIGIN: ${CORS_ORIGIN}
      MINIO_ENDPOINT: ${MINIO_ENDPOINT}
      MINIO_PORT: ${MINIO_PORT}
      MINIO_ACCESS_KEY: ${MINIO_ROOT_USER}
      MINIO_SECRET_KEY: ${MINIO_ROOT_PASSWORD}
      MINIO_BUCKET_NAME: ${MINIO_BUCKET_NAME}
      MINIO_USE_SSL: ${MINIO_USE_SSL}
      TZ: ${TZ}
    expose:
      - "5000"
    depends_on:
      mongodb:
        condition: service_healthy
        restart: true
      minio:
        condition: service_healthy
        restart: true
    healthcheck:
      test: [ "CMD", "node", "-e", "require('http').get('http://localhost:5000/health', (r) => process.exit(r.statusCode === 200 ? 0 : 1))" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 40s
    volumes:
      - backend_uploads:/app/uploads
    networks:
      - amdstore_network

  # SAB Lanyard Frontend React App (with Nginx Reverse Proxy)
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        - VITE_API_URL=${REACT_APP_API_URL:-http://localhost}
    pull_policy: always
    environment:
      VITE_API_URL: ${REACT_APP_API_URL:-http://localhost}
    container_name: amdstore_frontend
    restart: unless-stopped
    expose:
      - 80
    depends_on:
      backend:
        condition: service_started
    networks:
      - amdstore_network
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost/health" ]
      interval: 30s
      timeout: 3s
      retries: 3
      start_period: 10s

volumes:
  mongodb_data:
  minio_data:
  backend_uploads:


networks:
  amdstore_network:
    external: true
    name: multi-domain
